# Change these first
owner: AndrisaniSRL # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Andrisani Website
    url: https://www.andrisani.com.ar
  - name: Andrisani Socios Admin
    url: https://socios.andrisani.com.ar
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.andrisani.com.ar
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Andrisani -  **Upptime** Status page."
  introMessage: Esta web es un status page perteneciente a **Andrisani Servicios Sociales**. Cualquier inconveniente o duda contactarse via email a [contacto@andrisani.com.ar](mailto://contacto@andrisani.com.ar).
  navbar:
    - title: Andrisani Website
      href: https://www.andrisani.com.ar
    - title: Andrisani Socios Admin
      href: https://socios.andrisani.com.ar

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
